services:
  app:
    build: .
    env_file: .env
    mem_limit: ${MemoryLimit}
    command: >
      bash -c "sed -i 's/lagcompmode 1/lagcompmode ${LagCompMode}/' server.cfg 
      && sed -i 's/maxplayers 30/maxplayers ${MaxPlayers}/' server.cfg 
      && ./omp-server"
    ports:
      - ${Port}:7777/udp
    environment:
      - TZ=${TZ}
    volumes:
      - ./scripts/sqlite:/app/scripts/sqlite
      - ./logs:/app/logs

networks:
  default:
    name: 'gamemode-ctf'