services:
  app:
    build: .
    env_file: .env
    command: >
      bash -c "sed -i 's/lagcompmode 1/lagcompmode ${LagCompMode}/' server.cfg 
      && sed -i 's/maxplayers 30/maxplayers ${MaxPlayers}/' server.cfg 
      && ./samp03svr"
    ports:
      - ${Port}:7777/udp
    volumes:
      - ./scripts/sqlite:/app/scripts/sqlite

networks:
  default:
    name: 'gamemode-ctf'