//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTF.Application.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CTF.Application.Common.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no items in your weapon package.
        /// </summary>
        internal static string EmptyWeaponPackage {
            get {
                return ResourceManager.GetString("EmptyWeaponPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid rank has been passed.
        /// </summary>
        internal static string InvalidRank {
            get {
                return ResourceManager.GetString("InvalidRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid weapon has been passed.
        /// </summary>
        internal static string InvalidWeapon {
            get {
                return ResourceManager.GetString("InvalidWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name} is already in the weapon package.
        /// </summary>
        internal static string WeaponAlreadyExists {
            get {
                return ResourceManager.GetString("WeaponAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon has not been found.
        /// </summary>
        internal static string WeaponNotFound {
            get {
                return ResourceManager.GetString("WeaponNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name} was added to your weapon package.
        /// </summary>
        internal static string WeaponSuccessfullyAdded {
            get {
                return ResourceManager.GetString("WeaponSuccessfullyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name} has been removed from your weapon package.
        /// </summary>
        internal static string WeaponSuccessfullyRemoved {
            get {
                return ResourceManager.GetString("WeaponSuccessfullyRemoved", resourceCulture);
            }
        }
    }
}
