global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Data.Sqlite;
global using YeSql.Net;
global using CTF.Application.Common.Extensions;
global using CTF.Application.Common.Services;
global using CTF.Application.Players;
global using CTF.Application.Players.Accounts;
global using CTF.Application.Players.Ranks;