global using System.Collections;
global using System.Globalization;
global using System.Reflection;
global using System.Text.RegularExpressions;
global using System.Runtime.CompilerServices;
global using SampSharp.Core;
global using SampSharp.Entities;
global using SampSharp.Entities.SAMP;
global using Color = SampSharp.Entities.SAMP.Color;
global using SampSharp.Entities.SAMP.Commands;
global using SampSharp.Streamer.Entities;
global using SmartFormat;
global using SeztionParser;
global using Microsoft.Extensions.DependencyInjection;

global using CTF.Application.Common;
global using CTF.Application.Common.Resources;
global using CTF.Application.Players.Accounts;
global using CTF.Application.Players.Ranks;
global using CTF.Application.Teams;
global using CTF.Application.Teams.Flags;