global using System.Globalization;
global using System.Reflection;
global using CaptureTheFlag.Command.Admin;
global using CaptureTheFlag.Command.Public;
global using CaptureTheFlag.Controller;
global using CaptureTheFlag.Data;
global using CaptureTheFlag.DataBase;
global using CaptureTheFlag.DataBase.PlayerAccount;
global using static CaptureTheFlag.DataBase.PlayerAccount.Account;
global using static CaptureTheFlag.DataBase.DbCommand;
global using static CaptureTheFlag.DataBase.DbConnection;
global using CaptureTheFlag.Dialogs;
global using CaptureTheFlag.Dialogs.Extensions;
global using CaptureTheFlag.Events;
global using static CaptureTheFlag.Events.GameMode;
global using CaptureTheFlag.Utils;
global using CaptureTheFlag.PropertiesPlayer;
global using CaptureTheFlag.Map;
global using CaptureTheFlag.Permission;
global using static CaptureTheFlag.Map.CurrentMap;
global using static CaptureTheFlag.Utils.Validate;
global using CaptureTheFlag.Textdraw;
global using CaptureTheFlag.Teams;
global using static CaptureTheFlag.Command.Admin.CmdAdmin;
global using static CaptureTheFlag.Command.Public.CmdPublic;
global using static CaptureTheFlag.Command.Vip.CmdVip;
global using MySql.Data.MySqlClient;
global using SampSharp.Core;
global using SampSharp.GameMode.Controllers;
global using SampSharp.GameMode.Display;
global using SampSharp.GameMode.Events;
global using SampSharp.GameMode.SAMP;
global using SampSharp.GameMode.World;
global using SampSharp.GameMode.SAMP.Commands;
global using SampSharp.YSF;
global using SampSharp.Core.Natives.NativeObjects;
global using SampSharp.GameMode;
global using SampSharp.GameMode.Definitions;
global using SampSharp.Streamer.World;
global using SampSharp.GameMode.SAMP.Commands.PermissionCheckers;
global using IniParser;
global using Timer = SampSharp.GameMode.SAMP.Timer;
global using static CaptureTheFlag.Utils.Rand;
global using static SampSharp.GameMode.World.BasePlayer;
global using static CaptureTheFlag.Utils.ParseData;
global using static SampSharp.GameMode.Tools.KeyUtils;
global using DotEnv.Core;
global using CaptureTheFlag.Constants;