name: Capture.The.Flag

on: 
  push:
    branches: 
      - dev
  pull_request:
    branches:
      - dev
env:
  DOTNET_VERSION: '8.x'

jobs:
  unit_testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Execute unit tests
      run: |
        dotnet test ./tests/Application.Tests/CTF.Application.Tests.csproj -c Release